[package]
name = "runtime"
version = "0.1.0"
authors = ["James Dyer <jamesdyer199@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.103"
libc-print = "0.1.20"
