[package]
name = "runtime"
version = "0.1.0"
authors = ["James Dyer <jamesdyer199@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.103"
